=== ForceOverArea/Ngineer/neapolitan_json/neapolitan_model_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "The Neapolitan model file format.",
    "definitions": {
        "node_config": {
            "type": "object",
            "properties": {
                "potential": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "is_locked": {
                    "type": "boolean"
                },
                "metadata": {
                    "type": [ "object", "null" ]
                }
            }
        }
    },
    "type": "object",
    "properties": {
        "model_type": {
            "type": "string"
        },
        "nodes": {
            "type": "number"
        },
        "configuration": {
            "type": "object",
            "patternProperties": {
                "[0-9]+": {
                    "$ref": "#/definitions/node_config"
                }
            }
        },
        "elements": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "element_type": {
                        "type": "string"
                    },
                    "input": {
                        "type": "number"
                    },
                    "output": {
                        "type": "number"
                    },
                    "gain": {
                        "type": "array"
                    }
                }
            }
        }
    }
}

=== ForceOverArea/Ngineer/neapolitan/neapolitan_json/circuit.json
{
  "$schema": "./neapolitan_model_schema.json",
  "model_type": "ssdc_circuit",
  "nodes": 4,
  "configuration": {
    "0": {
      "potential": [
        0.0
      ],
      "is_locked": true,
      "metadata": null
    }
  },
  "elements": [
    {
      "element_type": "voltage_source",
      "input": 0,
      "output": 1,
      "gain": [
        3.0
      ]
    },
    {
      "element_type": "resistor",
      "input": 1,
      "output": 2,
      "gain": [
        2.0
      ]
    },
    {
      "element_type": "resistor",
      "input": 1,
      "output": 2,
      "gain": [
        2.0
      ]
    },
    {
      "element_type": "resistor",
      "input": 2,
      "output": 3,
      "gain": [
        1.0
      ]
    },
    {
      "element_type": "resistor",
      "input": 3,
      "output": 0,
      "gain": [
        1.0
      ]
    }
  ]
}
